let shopItemsData = [
  {
    id: "sharbat1",
    name: "شربت سن ایچ",
    price: 260,
    desc: "سه لیتری اناناسی",
    img: "../../images/sharbat-3-pineapple.jpg",
  },
  {
    id: "sharbat2",
    name: "شربت سن ایچ",
    price: 260,
    desc: "سه لیتری البالویی",
    img: "../../images/sharbat-3-cherry.jpg",
  },
  {
    id: "sharbat3",
    name: "شربت سن ایچ",
    price: 300,
    desc: "سه لیتری پرتقالی",
    img: "../../images/sharbat-3-orange.jpg",
  },
  {
    id: "chocolatePowder",
    name: "پودر کاکاو",
    price: 75,
    desc: "نیم کیلویی ترکیه",
    img: "../../images/chocolate-powder.jpg",
  },
  {
    id: "ghaleb1",
    name: "قالب",
    price: 18,
    desc: "قالب ژله",
    img: "../../images/ghaleb-1.jpg",
  },
  {
    id: "ghaleb2",
    name: "قالب",
    price: 18,
    desc: "قالب ژله",
    img: "../../images/ghaleb-2.jpg",
  },
  {
    id: "ghaleb3",
    name: "قالب",
    price: 18,
    desc: "قالب ژله",
    img: "../../images/ghaleb-3.jpg",
  },
  {
    id: "ghaleb4",
    name: "قالب",
    price: 18,
    desc: "قالب ژله",
    img: "../../images/ghaleb-4.jpg",
  },
  {
    id: "ghaleb5",
    name: "قالب",
    price: 18,
    desc: "قالب ژله",
    img: "../../images/ghaleb-5.jpg",
  },
  {
    id: "ghaleb6",
    name: "قالب",
    price: 18,
    desc: "قالب ژله",
    img: "../../images/ghaleb-6.jpg",
  },
  {
    id: "ghaleb7",
    name: "قالب",
    price: 18,
    desc: "قالب ژله",
    img: "../../images/ghaleb-7.jpg",
  },
  {
    id: "ghaleb8",
    name: "قالب",
    price: 18,
    desc: "قالب ژله",
    img: "../../images/ghaleb-8.jpg",
  },
];
